# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-25 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alias',
            field=models.CharField(default=1, max_length=245),
            preserve_default=False,
        ),
    ]
